name: 'Change jira issues status'
description: 'Move jira issues to a status and set link to github action'
inputs:
  jira-api-token:
    description: 'Jira api token'
    required: true
  jira-email:
    description: 'Jira email related to api token'
    required: true
  jira-base-url:
    description: 'Jira base url'
    required: true
  issues:
    description: 'Issues to move! It must be separated by ","'
    required: true
  to:
    description: 'Final status! It is case sensitive!'
    required: true
  from:
    description: 'Only if the issues are in this status!. It can be separated by ","'
    required: false
  avoid:
    description: "Status will be avoided, it only happen if you don't set from status. It can be separated by ','"
    required: false
  title:
    description: 'Title for github external link in Jira'
    required: false
outputs:
  moved-issues:
    description: 'How much issues was moved!'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'trello'
  color: 'blue'
